alias: door status notify
description: door status notify
triggers:
  - trigger: time_pattern
    minutes: "1"
conditions: []
actions:
  - action: rest_command.door_status
    response_variable: door_response
    data: {}
  - if:
      - condition: template
        value_template: "{{ door_response['status'] == 200 }}"
    then:
      - alias: Parse data
        variables:
          status: "{{ door_response['content']['status'] }}"
      - if:
          - condition: template
            value_template: "{{ status == 'open' }}"
        then:
          - action: notify.mobile_app_lars_pixel_6
            data:
              title: Door Status
              message: Door open
      - if:
          - condition: template
            value_template: "{{ status == 'close' }}"
        then:
          - action: notify.mobile_app_lars_pixel_6
            data:
              title: Door Status
              message: Door close
mode: single
