description: egj_alarm_system
triggers:
  - trigger: time_pattern
    minutes: /1
conditions:
  - alias: at sleep time
    condition: time
    after: "20:00:00"
    before: "08:00:00"
actions:
  - action: rest_command.egj_workhop_door
    response_variable: door_response
    data: {}
  - if:
      - condition: template
        value_template: "{{ door_response['status'] == 200 }}"
    then:
      - alias: Parse data
        variables:
          status: "{{ door_response['content']['status'] }}"
      - if:
          - condition: template
            value_template: "{{ status == 'open' }}"
        then:
          - action: light.turn_on
            target:
              entity_id: all
            data: {}
          - action: notify.mobile_app_lars_pixel_6
            data:
              title: Door Status
              message: Door open at sleep time
mode: single
